import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
// @ts-ignore: allow side-effect CSS import without type declarations
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Smart Travel",
  description: "Generated by create next app",
};

import { SelectionProvider } from "@/context/SelectionContext";
import { ToastProvider } from "@/components/ui/ToastProvider";
import SelectionPanel from "@/components/selection/SelectionPanel";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased`}>
        <SelectionProvider>
          <ToastProvider>
            <Navbar />
            <main className="grow">{children}</main>
            <SelectionPanel />
            <Footer />
          </ToastProvider>
        </SelectionProvider>
      </body>
    </html>
  );
}
